<%@ Page Language="C#" AutoEventWireup="true" CodeFile="sysManager_left.aspx.cs" Inherits="manager_sysManager_sysManager_left" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="Head1" runat="server">
    <title>无标题页</title>
    <link href="../../CSS/CSS.css" rel="stylesheet" type="text/css" />
</head>
<body style="margin-top: 0px; margin-bottom: 0px; margin-right:0px; margin-left:0px" class="css">
    <form id="form1" runat="server">
    <div>
        <table border="0" cellpadding="0" cellspacing="0" class="css" style="vertical-align: top;
            width: 240px; height: 470px; text-align: left; background-color: #dee9f9;">
            <tr>
                <td colspan="3" style="vertical-align: top; height: 50px; text-align: left">
                    <asp:ImageButton ID="systemManage" runat="server" Height="50px" ImageUrl="~/image/system/系统管理上.jpg"
                        OnClick="systemManage_Click" Width="240px" />
                    <asp:Panel ID="systemManagePanel" runat="server"  Visible="False">
                        <asp:TreeView ID="systemManagerTree" runat="server" AutoGenerateDataBindings="False"
                            ExpandDepth="0" Font-Size="13px">
                            <RootNodeStyle Font-Bold="True" Font-Size="15px" />
                            <NodeStyle ForeColor="Black" NodeSpacing="3px" />
                            <Nodes>
                                <asp:TreeNode Text="系统设置" Value="系统设置" SelectAction="Expand" Target="main">
                                    <asp:TreeNode Text="系统参数设置" Value="系统参数设置" NavigateUrl="~/manager/sysManager/systemManage/sys_parameterSet.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="菜单管理" Value="菜单管理" SelectAction="Expand">
                                    <asp:TreeNode Text="学生菜单管理" Value="学生菜单管理" NavigateUrl="~/manager/sysManager/systemManage/sys_studentMenuManage.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="老师菜单管理" Value="老师菜单管理" NavigateUrl="~/manager/sysManager/systemManage/sys_teacherMenuManage.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="权限管理" Value="权限管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看其他角色权限" Value="查看院系管理员权限" NavigateUrl="~/manager/sysManager/systemManage/sys_examineOtherRolePopedom.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="查看超级管理员权限" Value="查看超级管理员权限" NavigateUrl="~/manager/sysManager/systemManage/sys_examineSuperManagerPopedom.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="vertical-align: top; height: 50px; text-align: left">
                    <asp:ImageButton ID="studentManage" runat="server" Height="50px" ImageUrl="~/image/system/学生管理上.jpg"
                        OnClick="studentManage_Click" Width="240px" />
                    <asp:Panel ID="studentManagePanel" runat="server" >
                        <asp:TreeView ID="studentManageTree" runat="server" AutoGenerateDataBindings="False"
                            ExpandDepth="0" Font-Size="13px">
                            <RootNodeStyle Font-Bold="True" Font-Size="14px" />
                            <NodeStyle ForeColor="Black" NodeSpacing="3px" />
                            <Nodes>
                                <asp:TreeNode Text="基本信息管理" Value="基本信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找学生基本信息" Value="新建节点" NavigateUrl="~/manager/sysManager/studentManage/std_findStudentBasicInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加学生基本信息" Value="添加学生基本信息" NavigateUrl="~/manager/sysManager/studentManage/std_addStudentBasicInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="查找学生用户信息" Value="查找学生用户信息" NavigateUrl="~/manager/sysManager/studentManage/std_findStudentUserInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加学生用户信息" Value="添加学生用户信息" NavigateUrl="~/manager/sysManager/studentManage/std_addStudentUserInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="课表信息管理" Value="课表信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找学生课表" Value="查找学生课表" NavigateUrl="~/manager/sysManager/studentManage/std_findStudentCourseTable.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加学生课表" Value="添加学生课表" NavigateUrl="~/manager/sysManager/studentManage/std_addStudentCourseTable.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="选课信息管理" Value="选课信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode NavigateUrl="~/manager/sysManager/studentManage/std_addChooseCourse.aspx" Target="main"
                                        Text="添加选课" Value="添加选课"></asp:TreeNode>
                                    <asp:TreeNode Text="查找选课信息" Value="查找选课信息" NavigateUrl="~/manager/sysManager/studentManage/std_findChooseCourseInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加选课信息" Value="添加选课信息" NavigateUrl="~/manager/sysManager/studentManage/std_addChooseCourseInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode NavigateUrl="~/manager/sysManager/studentManage/std_findChooseCourseInfoDetail.aspx"
                                        Target="main" Text="查看选课详细信息" Value="查看选课详细信息"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="处分信息管理" Value="处分信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找处分信息" Value="查找处分信息" NavigateUrl="~/manager/sysManager/studentManage/std_findPunishInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加处分信息" Value="添加处分信息" NavigateUrl="~/manager/sysManager/studentManage/std_addPunishInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="奖学金信息管理" Value="奖学金信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找奖学金信息" Value="查找奖学金信息" NavigateUrl="~/manager/sysManager/studentManage/std_findScholarshipInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加奖学金信息" Value="添加奖学金信息" NavigateUrl="~/manager/sysManager/studentManage/std_addScholarshipInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="贫困生信息管理" Value="贫困生信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找贫困生信息" Value="查找贫困生信息" NavigateUrl="~/manager/sysManager/studentManage/std_findPoorStdInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加贫困生信息" Value="添加贫困生信息" NavigateUrl="~/manager/sysManager/studentManage/std_addPoorStdInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教师教学评估管理" Value="教师教学评估管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找教师评估结果" Value="查找教师评估结果" NavigateUrl="~/manager/sysManager/studentManage/std_findStdTeachingEvalution.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教师评估投票" Value="添加教师评估投票" NavigateUrl="~/manager/sysManager/studentManage/std_addStdTeachingEvalution.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="等级考试成绩管理" Value="等级考试成绩管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找等级考试成绩信息" Value="查找等级考试成绩信息" NavigateUrl="~/manager/sysManager/studentManage/std_findGradeTestMark.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加等级考试成绩信息" Value="添加等级考试成绩信息" NavigateUrl="~/manager/sysManager/studentManage/std_addGradeTestMark.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="等级考试报名管理" Value="四六级等级考试报名管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode NavigateUrl="~/manager/sysManager/studentManage/std_findGradeTestSignUpDetail.aspx"
                                        Target="main" Text="查找等级考试报名" Value="查找等级考试报名"></asp:TreeNode>
                                    <asp:TreeNode Text="添加等级考试报名" Value="添加等级考试报名信息" NavigateUrl="~/manager/sysManager/studentManage/std_addGradeTestSignUpInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode NavigateUrl="~/manager/sysManager/studentManage/std_addGradeTestSignUp.aspx"
                                        Target="main" Text="添加学生等级考试报名" Value="添加等级考试报名"></asp:TreeNode>
                                    <asp:TreeNode Text="查找等级考试报名信息" Value="查找等级考试报名信息" NavigateUrl="~/manager/sysManager/studentManage/std_findGradeTestSignUpInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="毕业生实习信息管理" Value="毕业生实习信息管理" Target="main" SelectAction="Expand">
                                    <asp:TreeNode Text="查找毕业生实习信息" Value="查找毕业生实习信息" NavigateUrl="~/manager/sysManager/studentManage/std_findGradPractiseInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加毕业生实习信息" Value="添加毕业生实习信息" NavigateUrl="~/manager/sysManager/studentManage/std_addGradPractiseInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="vertical-align: top; height: 50px; text-align: left">
                    <asp:ImageButton ID="teacherManage" runat="server" Height="50px" ImageUrl="~/image/system/老师管理上.jpg"
                        OnClick="teacherManage_Click" Width="240px" />
                    <asp:Panel ID="teacherManagePanel" runat="server" >
                        <asp:TreeView ID="teacherManagTree" runat="server" AutoGenerateDataBindings="False"
                            ExpandDepth="0" Font-Size="13px">
                            <RootNodeStyle Font-Bold="True" Font-Size="15px" />
                            <NodeStyle ForeColor="Black" NodeSpacing="3px" />
                            <Nodes>
                                <asp:TreeNode Text="教师基本信息管理" Value="教师基本信息管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查找教师基本信息" Value="查找教师基本信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTeaBasicInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教师基本信息" Value="添加教师信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_addTeaBasicInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教师在职信息管理" Value="教师在职信息管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查找教师获奖信息" Value="查找教师获奖信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTeacherExcellenceInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教师获奖信息" Value="添加教师获奖信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_addTeacherExcellenceInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="查找教师处分信息" Value="查找教师处分信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTeacherPunishInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教师处分信息" Value="添加教师处分信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_addTeacherPunishInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教师上传成绩管理" Value="教师上传成绩管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查找教师上传成绩信息" Value="查找教师上传成绩信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTransmitMarkInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教师上传成绩信息" Value="添加教师上传成绩信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_addTransmitMarkInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教师教学评估管理" Value="教师教学评估管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看教师评估结果" Value="查看教师评估结果" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTeachingEvalutionResult.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教师用户信息管理" Value="教师用户信息管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查找教师用户信息" Value="查找教师用户信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTeacherUserInfo.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教师用户信息" Value="添加教师用户信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_addTeacherUserInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教师课表信息管理" Value="教师课表信息管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查找教师课表信息" Value="查找教师课表信息" NavigateUrl="~/manager/sysManager/teacherManage/tea_findTeacherCourseTable.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="vertical-align: top; height: 50px; text-align: left">
                    <asp:ImageButton ID="unitManage" runat="server" Height="50px" ImageUrl="~/image/system/部门管理上.jpg"
                        OnClick="unitManage_Click" Width="240px" />
                    <asp:Panel ID="unitManagePanel" runat="server" >
                        <asp:TreeView ID="unitManageTree" runat="server" AutoGenerateDataBindings="False"
                            ExpandDepth="0" Font-Size="13px">
                            <RootNodeStyle Font-Bold="True" Font-Size="15px" />
                            <NodeStyle ForeColor="Black" NodeSpacing="3px" />
                            <Nodes>
                                <asp:TreeNode Text="部门管理" Value="部门管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看部门信息" Value="查找部门信息" NavigateUrl="~/manager/sysManager/unitManage/unit_findUnitInfoDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加部门信息" Value="添加部门信息" NavigateUrl="~/manager/sysManager/unitManage/unit_addUnitInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="院系管理" Value="院系管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查找院系信息" Value="查找院系信息" NavigateUrl="~/manager/sysManager/unitManage/unit_findCollegeInfoDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加院系信息" Value="添加院系信息" NavigateUrl="~/manager/sysManager/unitManage/unit_addCollegeInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="教学班管理" Value="教学班管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看教学班" Value="查看教学班" NavigateUrl="~/manager/sysManager/unitManage/unit_findTeachedClassInfoDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加教学班" Value="添加教学班" NavigateUrl="~/manager/sysManager/unitManage/unit_addTeachedClassInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="行政班管理" Value="行政班管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看行政班" Value="查找行政班" NavigateUrl="~/manager/sysManager/unitManage/unit_findAdminClassInfoDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加行政班" Value="添加行政班" NavigateUrl="~/manager/sysManager/unitManage/unit_addAdminClassInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="部门新闻管理" Value="部门新闻管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看部门新闻信息" Value="查看部门新闻信息" NavigateUrl="~/manager/sysManager/unitManage/unit_findUnitNewsDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加部门新闻信息" Value="添加院系新闻信息" NavigateUrl="~/manager/sysManager/unitManage/unit_addUnitNews.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="院系新闻管理" Value="院系新闻管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看院系新闻信息" Value="查看院系新闻信息" NavigateUrl="~/manager/sysManager/unitManage/unit_findCollegeNewsDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加院系新闻信息" Value="添加院系新闻信息" NavigateUrl="~/manager/sysManager/unitManage/unit_addCollegeNews.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="学院专业管理" Value="学院专业管理" SelectAction="Expand">
                                    <asp:TreeNode Text="查看学院专业" Value="查看学院专业" NavigateUrl="~/manager/sysManager/unitManage/unit_findSpecialityInfoDetail.aspx" Target="main"></asp:TreeNode>
                                    <asp:TreeNode Text="添加学院专业" Value="添加学院专业" NavigateUrl="~/manager/sysManager/unitManage/unit_addSpecialityInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="vertical-align: top; height: 50px; text-align: left">
                    <asp:ImageButton ID="informationManage" runat="server" Height="50px" ImageUrl="~/image/system/信息统计上.jpg"
                        OnClick="informationStat_Click" Width="240px" />
                    <asp:Panel ID="infomationStatPanel" runat="server" >
                        <asp:TreeView ID="infomationStatTree" runat="server" AutoGenerateDataBindings="False"
                            ExpandDepth="0" Font-Size="13px">
                            <RootNodeStyle Font-Bold="True" Font-Size="15px" />
                            <NodeStyle ForeColor="Black" NodeSpacing="3px" />
                            <Nodes>
                                <asp:TreeNode Text="各院系贫困生信息统计" Value="各院系贫困生信息统计" SelectAction="Expand">
                                    <asp:TreeNode Text="各院系贫困生信息统计" Value="各院系贫困生信息统计" NavigateUrl="~/manager/sysManager/infomationStat/info_collegePoorStd.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="各院系奖学金信息统计" Value="各院系奖学金信息统计" SelectAction="Expand">
                                    <asp:TreeNode Text="各院系奖学金信息统计" Value="各院系奖学金信息统计" NavigateUrl="~/manager/sysManager/infomationStat/info_collegeScholarshipInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="各院系受处分信息统计" Value="各院系受处分信息统计" SelectAction="Expand">
                                    <asp:TreeNode Text="各院系受处分信息统计" Value="各院系受处分信息统计" NavigateUrl="~/manager/sysManager/infomationStat/info_collegePunishInfo.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode Text="各院系年级成绩排名统计" Value="各院系年级成绩排名统计" SelectAction="Expand">
                                    <asp:TreeNode Text="各院系年级成绩排名统计" Value="各院系年级成绩排名统计" NavigateUrl="~/manager/sysManager/infomationStat/info_collegeStdMark.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="vertical-align: top; height: 50px; text-align: left">
                    <asp:ImageButton ID="managerManage" runat="server" Height="50px" ImageUrl="~/image/system/管理员管理上.jpg"
                        OnClick="managerManage_Click" Width="240px" />
                    <asp:Panel ID="managerManagePanel" runat="server" >
                        <asp:TreeView ID="managerManageTree" runat="server" AutoGenerateDataBindings="False"
                            ExpandDepth="0" Font-Size="13px">
                            <RootNodeStyle Font-Bold="True" Font-Size="15px" />
                            <NodeStyle ForeColor="Black" NodeSpacing="3px" />
                            <Nodes>
                                <asp:TreeNode NavigateUrl="http://www2.ncwu.edu.cn/jiaowu/"
                                    Target="main" Text="教务处主页" Value="教务处主页" SelectAction="Expand">
                                    <asp:TreeNode NavigateUrl="http://www2.ncwu.edu.cn/jiaowu/"
                                        Target="main" Text="教务处主页" Value="教务处主页"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode SelectAction="Expand" Text="查看管理员" Value="查看管理员">
                                    <asp:TreeNode Text="查看系统管理员" Value="查看系统管理员" Target="main" NavigateUrl="~/manager/sysManager/managerManage/man_findManagerDetail.aspx"></asp:TreeNode>
                                </asp:TreeNode>
                                <asp:TreeNode SelectAction="Expand" Target="main" Text="添加管理员" Value="添加管理员">
                                    <asp:TreeNode Text="添加系统管理员" Value="添加系统管理员" NavigateUrl="~/manager/sysManager/managerManage/man_addManager.aspx" Target="main"></asp:TreeNode>
                                </asp:TreeNode>
                            </Nodes>
                        </asp:TreeView>
                    </asp:Panel>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="vertical-align: top; height: 170px; text-align: left">
                    &nbsp;
                </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
